# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class Direction(str, Enum):
    North_South = "North South"
    East_West = "East West"


class SurveyLines(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    direction: Optional[Direction] = Field(
        "North South",
        description="Compass bearing the survey lines will run from the region of interest (0 = North, 90 = East).",
        title="Survey Direction (degrees)",
    )
    spacing: Optional[int] = Field(
        500,
        description="Distance in metres between adjacent survey lines across the region of interest.",
        title="Line Spacing (m)",
    )


class DrawAerialSurveyLines(BaseModel):
    survey_lines: Optional[SurveyLines] = Field(None, title="")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class DownloadFile(BaseModel):
    url: str = Field(..., description="URL to download a file", title="URL")


class LocalFile(BaseModel):
    file_path: str = Field(
        ..., description="Path to a local file", title="Local file path"
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class RetrieveFileParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    input_method: Union[DownloadFile, LocalFile] = Field(..., title="Input Method")


class DefineRegionOfInterest(BaseModel):
    retrieve_file_params: Optional[RetrieveFileParams] = Field(None, title="")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set workflow details",
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time range"
    )
    Define_Region_of_Interest: Optional[DefineRegionOfInterest] = Field(
        None,
        alias="Define Region of Interest",
        description="Define the region of interest for the aerial survey by uploading a geospatial file (GeoJSON, GeoPackage, or Shapefile) that contains the boundary of the area to be surveyed. This file will be loaded and processed to generate the survey lines.",
    )
    Draw_Aerial_Survey_Lines: Optional[DrawAerialSurveyLines] = Field(
        None,
        alias="Draw Aerial Survey Lines",
        description="Generate aerial survey lines across the defined region of interest based on the specified direction and spacing. The survey lines will be created as a geospatial dataframe and visualized on an interactive map.",
    )
